apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dep
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Release.Name }}
          image: structurizr/lite:latest
          imagePullPolicy: Always
          port: 8080
          volumeMounts:
            - name: pvc-{{ .Release.Name }}
              mountPath: /usr/local/structurizr
