apiVersion: v1
kind: Service
metadata:
  name: svc-{{ .Release.Name }}
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
  type: NodePort
