apiVersion: v1
kind: Service
metadata:
  name: svc-{{ .Release.Name }}
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
